### ISSUE TITLE
真的需要开启 --privileged=true 么？

### ISSUE THREAD

**Issue by vizv** [yinheli/docker-thunder-xware#2]
我打算写一篇关于 Docker 封装 xware 的文……然后看到你的 repo 决定不再重造轮子……但是 `run.sh` 中的 `--privileged=true` 真的需要么？我之前手动配置的时候当时没有加上 --privileged=true 也是可以的

**Comment by yinheli** [comment]
这个不是必须的.

**Comment by vizv** [comment]
感觉那样还是去掉比较好……安全原因

**Comment by yinheli** [comment]
@vizv 移除了.

**Comment by vizv** [comment]
:+1:
