### ISSUE TITLE
【Q】为啥直接运行portal，容器过几秒会出错退出？

### ISSUE THREAD

**Issue by cuteribs-1** [yinheli/docker-thunder-xware#4]
我看到你的start.sh里是下面这样写的，不明白为什么。
set -e

while true; do
    pid=`ps -ef|grep vod_httpserver|grep -v grep|awk '{print $2}'`
    if [ -z "$pid" ]; then
        ./bin/portal
    else
        sleep 60
    fi
done

**Comment by yinheli** [comment]
xware 是个后台进程. docker 直接启动后整个容器会退出.  故写了个 bash 脚本每分钟检测迅雷是否退出. 
另外bash脚本不会退出. docker app 则一直运行.
